### 1. Obtener todos los contratos (Sin filtros)
GET http://localhost:8000/api/contratos?page=1&page_size=10
Content-Type: application/json

### 21. Obtener todos los contratos (Sin filtros)
GET http://localhost:8000/api/contratos?inquilino_num_identificacion=12
Content-Type: application/json

### 2. Filtrar por Cédula del Inquilino (Usando el Alias definido)
# Antes: inquilino_id=2
# Ahora: usamos el alias que mapea a inquilino__numero_identificacion
GET http://localhost:8000/api/contratos?status=true
Content-Type: application/json

### 3. Filtrar por Número de Departamento y Edificio
# Probando la relación profunda: departamento__edificio__nombre
GET http://localhost:8000/api/contratos?num_departamento=202&nombre_edificio=Torre%20Aviadores
Content-Type: application/json

### 4. Crear Contrato - EXITOSO
# Nota: inquilino_id y departamento_id siguen igual porque son campos de ContratoCrear
POST http://localhost:8000/api/contratos
Content-Type: application/json

{
  "numero_identificacion_inquilino": "1234567890",
  "numero_departamento": "222",
  "frecuencia_pago": "mensual",
  "monto": 2100000.00,
  "dia_pago": 10,
  "fecha_inicio": "2026-04-01",
  "fecha_fin": "2027-04-01",
  "status": true,
  "al_dia": true,
  "descripcion": "Contrato de alquiler residencial - Unidad 202"
}

### 5. Crear Contrato - ERROR (Validación Pydantic: fecha_inicio > fecha_fin)
POST http://localhost:8000/api/contratos
Content-Type: application/json

{
  "inquilino_id": 2,
  "departamento_id": 11,
  "frecuencia_pago": "mensual",
  "monto": 1800000.00,
  "dia_pago": 5,
  "fecha_inicio": "2026-12-01",
  "fecha_fin": "2026-01-01"
}

### 6. Crear Contrato - ERROR (Frecuencia 'diario' no está en el Literal)
POST http://localhost:8000/api/contratos
Content-Type: application/json

{
  "numero_identificacion_inquilino": "1234567890",
  "numero_departamento": "101",
  "frecuencia_pago": "diario",
  "monto": 50000.00,
  "dia_pago": 1,
  "fecha_inicio": "2026-01-01",
  "fecha_fin": "2026-02-01"
}

### 7. Actualizar Contrato - EXITOSO
PUT http://localhost:8000/api/contratos/8
Content-Type: application/json

{
  "monto": 2250000.00,
  "al_dia": false,
  "descripcion": "Actualización de monto por ajuste anual"
}

### 8. Actualizar Contrato - ERROR (Día de pago 32 falla validación Field(le=31))
PUT http://localhost:8000/api/contratos/1
Content-Type: application/json

{
  "dia_pago": 32
}

### 9. Eliminar Contrato - EXITOSO
DELETE http://localhost:8000/api/contratos/7
Content-Type: application/json

### 10. Listar con paginación
GET http://localhost:8000/api/contratos?page=1&page_size=5
Content-Type: application/json