# Generated by Django 6.0.3 on 2026-03-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_remove_contratos_id_departamento_and_more'),
        ('edificios', '0004_remove_departamentos_id_edificio_and_more'),
        ('inquilinos', '0002_rename_numero_identificion_inquilinos_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='departamento',
            field=models.ForeignKey(db_column='departamento_id', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='edificios.departamentos'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inquilino',
            field=models.ForeignKey(db_column='inquilino_id', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='inquilinos.inquilinos'),
        ),
    ]
