# Generated by Django 6.0.3 on 2026-04-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0004_remove_departamentos_id_edificio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='edificio',
            field=models.ForeignKey(db_column='edificio_id', on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='edificios.edificios'),
        ),
    ]
